name: Build and deploy Node.js app to Azure Web App - coejoyn(coejoyn-dev)

on:
  # push:
  #   branches:
  #     - dev
  workflow_dispatch:
    inputs:
      deploy_reason:
        description: "Reason for deployment"
        required: false
        default: "Manual deployment"
      confirm_deploy:
        description: 'Type "deploy" to confirm'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: npm install, build, and test
        env:
          TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
          TINA_CLIENT_ID: ${{ secrets.TINA_CLIENT_ID }}
          NEXT_PUBLIC_TINA_CLIENT_ID: ${{ secrets.TINA_CLIENT_ID }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          TINA_BRANCH: dev
          NEXT_PUBLIC_TINA_BRANCH: dev
        run: |
          cd frontend
          npm install
          npm run build -- --no-lint
          cp -r public .next/standalone/public
          cp -r .next/static .next/standalone/.next/static

      - name: Zip artifact for deployment
        run: |
          cd frontend/.next/standalone
          zip -r ../../../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: dev

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "coejoyn"
          slot-name: "coejoyn-dev"
          package: .
          publish-profile: ${{ secrets.__publishingprofilesecretname__ }}
