name: Build and deploy Next.js Tina CMS app to Azure Web App - coejoyn

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build Next.js app
        env:
          TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
          TINA_CLIENT_ID: ${{ secrets.TINA_CLIENT_ID }}
          NEXT_PUBLIC_TINA_CLIENT_ID: ${{ secrets.TINA_CLIENT_ID }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
        run: |
          cd frontend
          npm run build

      - name: Create deployment package
        run: |
          cd frontend
          cp -r .next ./deployment-package/
          cp -r public ./deployment-package/ 2>/dev/null || true
          cp package*.json ./deployment-package/
          cp next.config.* ./deployment-package/ 2>/dev/null || true

      - name: Install production dependencies
        run: |
          cd frontend/deployment-package
          npm ci --only=production

      - name: Zip artifact for deployment
        run: |
          cd frontend
          zip -r ../release.zip deployment-package/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "coejoyn"
          slot-name: "coejoyn-dev"
          package: ./deployment-package
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
